### ISSUE TITLE
Fix failed test of opensuse/leap

### ISSUE THREAD

**Issue by vi9076** [acmesh-official/acmetest#5]
Hi, I'm currently trying to fix the failed test of "opensuse/leap".

From the commit history and with several experiments, I've figured out a working fix for me.
So I'd like to have a discussion first, to have a proper fix for the project in the end.

Current definition for opensuse/leap in plat.conf:
```
-opensuse|zypper update -y |zypper install  -y  |tar,openssl,cron,socat,curl,libidn|
opensuse/leap|
```

My working fix:
```
-opensuse/leap|zypper rr repo-non-oss repo-update-non-oss && zypper update -y |zypper install  -y |tar,openssl,cron,socat,curl,gzip,unzip|
opensuse/leap:latest|
```

Discussions:
- `zypper rr repo-non-oss repo-update-non-oss`: Taken from commit history and adapted to the repo name for openSUSE Leap 15. My guess is that by removing unnecessary package repos, it saves many seconds during a test run.

- `gzip`: Apparently gzip is not in the image of opensuse/leap:15 on Docker Hub. So it's necessary to explicitly add it.

- `unzip`: According to commit history of `plat.conf`, `unzip` was removed from all distros and added back only to ubuntu. I'm not sure the purpose. But for NGROK test to work in opensuse/leap, `unzip` is required to extract ngrok binary.  

- `libidn` (Removed): The package repo do not have `libidn`, causing the test to fail. A package with the name `libidn2-0` is already installed. I'm not sure the whether the proper fix is to remove it or to replace with another libidn package.

```
S | Name            | Summary                                               | Type
--+-----------------+-------------------------------------------------------+--------
  | libidn-devel    | Development files for libidn                          | package
  | libidn-tools    | Command line utility to convert Int. Domain Names     | package
  | libidn11        | Support for Internationalized Domain Names (IDN)      | package
  | libidn11-32bit  | Support for Internationalized Domain Names (IDN)      | package
i | libidn2-0       | Support for Internationalized Domain Names (IDN)      | package
  | libidn2-0-32bit | Support for Internationalized Domain Names (IDN)      | package
  | libidn2-devel   | Include Files and Libraries mandatory for Development | package
  | libidn2-lang    | Translations for package libidn2                      | package
  | libidn2-tools   | Command line utility to convert Int. Domain Names     | package
  | perl-Net-LibIDN | Net::LibIDN Perl module                               | package

```

**Comment by Neilpang** [comment]
please add "libidn2-0" and send me your PR.

Thanks.

**Comment by Neilpang** [comment]
maybe  "libidn2-tools" ?

**Comment by vi9076** [comment]
I'll test with $TEST_IDN enabled, to make the dependency clear. Please wait.

**Comment by vi9076** [comment]
Current status:
```
-opensuse/leap|zypper rr repo-non-oss repo-update-non-oss && zypper update -y |zypper install  -y  |tar,openssl,cron,socat,curl,libidn-tools,gzip,unzip|
opensuse/leap:latest|
```

1. Should be sufficient for running default tests 1-10, 12-19
Tests skipped by default: 11: IPv6, 20: IDN, 21: DNS API

2.  For Test 20: IDN, the package `libidn-tools` provides the required executable `idn`, used by `acme.sh`. 

I've send a draft PR.

PS. There's another issue running `idn` command in opensuse/leap. I'll create another issue with several IDN-related topics. The opensuse/leap-specific one is:
An extra environment variable `$LANG` is required for `idn` to work. Is there a proper way to set environment variables in the unit test framework?
```
552f40cd57c8:/ # idn 中文
idn: could not convert from ANSI_X3.4-1968 to UTF-8
552f40cd57c8:/ # LANG=en_US.UTF-8 idn 中文
xn--fiq228c
```
